"""empty message

Revision ID: 392b36a8f6d8
Revises: b6cdfed11529
Create Date: 2024-07-24 11:23:13.777236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392b36a8f6d8'
down_revision = 'b6cdfed11529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('gravity', sa.String(length=100), nullable=False),
    sa.Column('climate', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    # ### end Alembic commands ###
