"""empty message

Revision ID: 807420e3e6d0
Revises: 392b36a8f6d8
Create Date: 2024-07-24 11:24:03.484497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807420e3e6d0'
down_revision = '392b36a8f6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
