"""empty message

Revision ID: b784a6aba06a
Revises: 74726d1f94a1
Create Date: 2024-07-24 11:44:29.238906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b784a6aba06a'
down_revision = '74726d1f94a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mass', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('people_User_id_fkey', type_='foreignkey')
        batch_op.drop_column('first_name')
        batch_op.drop_column('User_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('User_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('people_User_id_fkey', 'user', ['User_id'], ['id'])
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('mass')
        batch_op.drop_column('description')

    op.drop_table('people_favorite')
    # ### end Alembic commands ###
